api:
  key: FlTERFkvGVcEY1NaUgj16ZctbimEdmXMvdAiH3m0
  url: http://192.168.178.160:2283/api
  album: null
  album_by_year: true
  delete_remote_on_local_delete: false
watchdog:
  recursive: true
  directories:
    - C:\Users\Guido\Pictures\
