api:
  key: apikey12345
  url: https://immich.domain.test/api
  album: null
  album_by_year: true
  delete_remote_on_local_delete: false
watchdog:
  recursive: true
  directories:
    - C:\Users\test\Pictures\
